[2024-10-29T22:32:37.674+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-29T22:32:37.688+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_top_100.extract_spotify_data manual__2024-10-29T22:27:34.060451+00:00 [queued]>
[2024-10-29T22:32:37.694+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_top_100.extract_spotify_data manual__2024-10-29T22:27:34.060451+00:00 [queued]>
[2024-10-29T22:32:37.694+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-29T22:32:37.703+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_spotify_data> on 2024-10-29 22:27:34.060451+00:00
[2024-10-29T22:32:37.710+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=182) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-29T22:32:37.710+0000] {standard_task_runner.py:72} INFO - Started process 184 to run task
[2024-10-29T22:32:37.711+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spotify_top_100', 'extract_spotify_data', 'manual__2024-10-29T22:27:34.060451+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/# spotify_dag.py', '--cfg-path', '/tmp/tmpmmuv8fl9']
[2024-10-29T22:32:37.712+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask extract_spotify_data
[2024-10-29T22:32:37.749+0000] {task_command.py:467} INFO - Running <TaskInstance: spotify_top_100.extract_spotify_data manual__2024-10-29T22:27:34.060451+00:00 [running]> on host 1ff9c74e23c3
[2024-10-29T22:32:37.807+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_top_100' AIRFLOW_CTX_TASK_ID='extract_spotify_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T22:27:34.060451+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-29T22:27:34.060451+00:00'
[2024-10-29T22:32:37.808+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-29T22:32:37.809+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-29T22:32:37.809+0000] {logging_mixin.py:190} INFO - Current task name:extract_spotify_data state:running start_date:2024-10-29 22:32:37.688694+00:00
[2024-10-29T22:32:37.810+0000] {logging_mixin.py:190} INFO - Dag name:spotify_top_100 and current dag run status:running
[2024-10-29T22:32:37.810+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-29T22:32:37.817+0000] {base.py:84} INFO - Retrieving connection 'spotify_credentials'
[2024-10-29T22:32:37.979+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/oauth2.py", line 256, in _request_access_token
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/# spotify_dag.py", line 30, in get_spotify_data
    results = sp.playlist_tracks(playlist_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/client.py", line 698, in playlist_tracks
    return self.playlist_items(playlist_id, fields, limit, offset,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/client.py", line 722, in playlist_items
    return self._get(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/client.py", line 327, in _get
    return self._internal_call("GET", url, payload, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/client.py", line 251, in _internal_call
    headers = self._auth_headers()
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/client.py", line 242, in _auth_headers
    token = self.auth_manager.get_access_token(as_dict=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/oauth2.py", line 229, in get_access_token
    token_info = self._request_access_token()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/oauth2.py", line 260, in _request_access_token
    self._handle_oauth_error(http_error)
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/oauth2.py", line 139, in _handle_oauth_error
    raise SpotifyOauthError(
spotipy.oauth2.SpotifyOauthError: error: invalid_client, error_description: Invalid client
[2024-10-29T22:32:37.990+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-29T22:32:37.991+0000] {logging_mixin.py:190} INFO - Task start:2024-10-29 22:32:37.688694+00:00 end:2024-10-29 22:32:37.990416+00:00 duration:0.301722
[2024-10-29T22:32:37.991+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_spotify_data> dag:<DAG: spotify_top_100> dagrun:<DagRun spotify_top_100 @ 2024-10-29 22:27:34.060451+00:00: manual__2024-10-29T22:27:34.060451+00:00, state:running, queued_at: 2024-10-29 22:27:34.072840+00:00. externally triggered: True>
[2024-10-29T22:32:37.992+0000] {logging_mixin.py:190} INFO - Failure caused by error: invalid_client, error_description: Invalid client
[2024-10-29T22:32:37.992+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=spotify_top_100, task_id=extract_spotify_data, run_id=manual__2024-10-29T22:27:34.060451+00:00, execution_date=20241029T222734, start_date=20241029T223237, end_date=20241029T223237
[2024-10-29T22:32:38.002+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-29T22:32:38.003+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 30 for task extract_spotify_data (error: invalid_client, error_description: Invalid client; 184)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/oauth2.py", line 256, in _request_access_token
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/# spotify_dag.py", line 30, in get_spotify_data
    results = sp.playlist_tracks(playlist_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/client.py", line 698, in playlist_tracks
    return self.playlist_items(playlist_id, fields, limit, offset,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/client.py", line 722, in playlist_items
    return self._get(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/client.py", line 327, in _get
    return self._internal_call("GET", url, payload, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/client.py", line 251, in _internal_call
    headers = self._auth_headers()
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/client.py", line 242, in _auth_headers
    token = self.auth_manager.get_access_token(as_dict=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/oauth2.py", line 229, in get_access_token
    token_info = self._request_access_token()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/oauth2.py", line 260, in _request_access_token
    self._handle_oauth_error(http_error)
  File "/home/airflow/.local/lib/python3.12/site-packages/spotipy/oauth2.py", line 139, in _handle_oauth_error
    raise SpotifyOauthError(
spotipy.oauth2.SpotifyOauthError: error: invalid_client, error_description: Invalid client
[2024-10-29T22:32:38.045+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-29T22:32:38.063+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29T22:32:38.066+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
